### ISSUE TITLE
Display basic infos about a group in a group page

### ISSUE THREAD

**Issue by davinov** [davinov/teledex#14]
## TODO
- [x] Use a /group/:id URL
- [x] Display the name of the group
- [x] Display the description of the group
- [ ] Display an icon for the group
- [ ] Display if the group is private or not
- [ ] Display the members if available
- [ ] Display a container for the widgets of the group (see Issue #13)
